on:
  push:
    branches:
      - "RC-[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]" # RC-YYYY-MM-DD

jobs:
  release-candidate-tags:
    runs-on: ubuntu-latest
    steps:
      - name:
        id: run-rc-branch-action
        uses: kazoohr/rc-branch-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
